[package]
name = "npc-sense"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
add_one = { path = "../add_one" }
rand = "0.8.5"
webrtc = "0.8.0"
serde = "1.0.185"