[package]
name = "sou"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
webrtc = "0.9.0"
serde = "1.0.185"
serde_json = "1.0.105"
tokio = "1.32.0"
anyhow = "1.0.75"